from freezegun import freeze_time
import pytest


from entities import FightStatsByRound
from parsers import FightStatByRoundParser
from tests import FIGHT_RESPONSE_VALID_PATH
from tests.utils import load_html_response_from_file


@pytest.fixture
def fight_stat_by_round_parser_valid() -> FightStatByRoundParser:
    fight_stat_by_round_response = load_html_response_from_file(
        FIGHT_RESPONSE_VALID_PATH
    )

    return FightStatByRoundParser(fight_stat_by_round_response)


@freeze_time("2000-01-01 00:00:00", tz_offset=0)
def test_fight_stat_by_round_parse_response_valid(
    fight_stat_by_round_parser_valid: FightStatByRoundParser,
) -> None:
    parsed_response = list(fight_stat_by_round_parser_valid.parse_response())

    expected_response_fighter_1_round_1 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="92b919ea-9d7f-52b8-b17d-96587b3432bc",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="957ba518-e9ac-576b-92ef-8d60d89e73a1",
        round=1,
        total_strikes_landed=42,
        total_strikes_attempted=42,
        significant_strikes_landed=6,
        significant_strikes_attempted=6,
        significant_strikes_landed_head=5,
        significant_strikes_attempted_head=5,
        significant_strikes_landed_body=0,
        significant_strikes_attempted_body=0,
        significant_strikes_landed_leg=1,
        significant_strikes_attempted_leg=1,
        significant_strikes_landed_distance=1,
        significant_strikes_attempted_distance=1,
        significant_strikes_landed_clinch=1,
        significant_strikes_attempted_clinch=1,
        significant_strikes_landed_ground=4,
        significant_strikes_attempted_ground=4,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=0,
        control_time_minutes=2,
        control_time_seconds=21,
        submissions_attempted=0,
        reversals=1,
    )

    expected_response_fighter_1_round_2 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="90da4657-ae74-5178-ba00-5e61d3256c12",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="957ba518-e9ac-576b-92ef-8d60d89e73a1",
        round=2,
        total_strikes_landed=32,
        total_strikes_attempted=49,
        significant_strikes_landed=32,
        significant_strikes_attempted=49,
        significant_strikes_landed_head=12,
        significant_strikes_attempted_head=26,
        significant_strikes_landed_body=6,
        significant_strikes_attempted_body=6,
        significant_strikes_landed_leg=14,
        significant_strikes_attempted_leg=17,
        significant_strikes_landed_distance=31,
        significant_strikes_attempted_distance=48,
        significant_strikes_landed_clinch=1,
        significant_strikes_attempted_clinch=1,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=1,
        takedowns_attempted=1,
        control_time_minutes=0,
        control_time_seconds=2,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_1_round_3 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="2370f679-da4f-5a0c-bbc9-2d0e4110ab90",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="957ba518-e9ac-576b-92ef-8d60d89e73a1",
        round=3,
        total_strikes_landed=28,
        total_strikes_attempted=44,
        significant_strikes_landed=21,
        significant_strikes_attempted=36,
        significant_strikes_landed_head=16,
        significant_strikes_attempted_head=28,
        significant_strikes_landed_body=1,
        significant_strikes_attempted_body=3,
        significant_strikes_landed_leg=4,
        significant_strikes_attempted_leg=5,
        significant_strikes_landed_distance=18,
        significant_strikes_attempted_distance=32,
        significant_strikes_landed_clinch=2,
        significant_strikes_attempted_clinch=2,
        significant_strikes_landed_ground=1,
        significant_strikes_attempted_ground=2,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=0,
        control_time_minutes=0,
        control_time_seconds=54,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_1_round_4 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="f0fcc8cb-7062-530e-949f-79f87ef81f5e",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="957ba518-e9ac-576b-92ef-8d60d89e73a1",
        round=4,
        total_strikes_landed=50,
        total_strikes_attempted=65,
        significant_strikes_landed=25,
        significant_strikes_attempted=40,
        significant_strikes_landed_head=19,
        significant_strikes_attempted_head=33,
        significant_strikes_landed_body=5,
        significant_strikes_attempted_body=5,
        significant_strikes_landed_leg=1,
        significant_strikes_attempted_leg=2,
        significant_strikes_landed_distance=21,
        significant_strikes_attempted_distance=35,
        significant_strikes_landed_clinch=4,
        significant_strikes_attempted_clinch=5,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=0,
        control_time_minutes=0,
        control_time_seconds=4,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_1_round_5 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="b0d47741-13c9-5fc1-8081-61f04584388f",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="957ba518-e9ac-576b-92ef-8d60d89e73a1",
        round=5,
        total_strikes_landed=38,
        total_strikes_attempted=63,
        significant_strikes_landed=37,
        significant_strikes_attempted=62,
        significant_strikes_landed_head=26,
        significant_strikes_attempted_head=50,
        significant_strikes_landed_body=6,
        significant_strikes_attempted_body=7,
        significant_strikes_landed_leg=5,
        significant_strikes_attempted_leg=5,
        significant_strikes_landed_distance=32,
        significant_strikes_attempted_distance=56,
        significant_strikes_landed_clinch=5,
        significant_strikes_attempted_clinch=6,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=3,
        control_time_minutes=0,
        control_time_seconds=0,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_2_round_1 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="8b84e694-5239-579a-ad96-9926e7252681",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="1fa816e9-e0c1-56b8-a267-4daf7b1e07ab",
        round=1,
        total_strikes_landed=1,
        total_strikes_attempted=1,
        significant_strikes_landed=1,
        significant_strikes_attempted=1,
        significant_strikes_landed_head=0,
        significant_strikes_attempted_head=0,
        significant_strikes_landed_body=1,
        significant_strikes_attempted_body=1,
        significant_strikes_landed_leg=0,
        significant_strikes_attempted_leg=0,
        significant_strikes_landed_distance=1,
        significant_strikes_attempted_distance=1,
        significant_strikes_landed_clinch=0,
        significant_strikes_attempted_clinch=0,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=1,
        takedowns_attempted=2,
        control_time_minutes=1,
        control_time_seconds=58,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_2_round_2 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="62585682-b634-5137-a0de-bfecd6c7ed61",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="1fa816e9-e0c1-56b8-a267-4daf7b1e07ab",
        round=2,
        total_strikes_landed=10,
        total_strikes_attempted=30,
        significant_strikes_landed=10,
        significant_strikes_attempted=30,
        significant_strikes_landed_head=6,
        significant_strikes_attempted_head=21,
        significant_strikes_landed_body=3,
        significant_strikes_attempted_body=7,
        significant_strikes_landed_leg=1,
        significant_strikes_attempted_leg=2,
        significant_strikes_landed_distance=10,
        significant_strikes_attempted_distance=29,
        significant_strikes_landed_clinch=0,
        significant_strikes_attempted_clinch=1,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=3,
        control_time_minutes=0,
        control_time_seconds=0,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_2_round_3 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="7073a01a-bfb3-5070-94cf-928b432fac2f",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="1fa816e9-e0c1-56b8-a267-4daf7b1e07ab",
        round=3,
        total_strikes_landed=13,
        total_strikes_attempted=25,
        significant_strikes_landed=13,
        significant_strikes_attempted=25,
        significant_strikes_landed_head=4,
        significant_strikes_attempted_head=15,
        significant_strikes_landed_body=6,
        significant_strikes_attempted_body=7,
        significant_strikes_landed_leg=3,
        significant_strikes_attempted_leg=3,
        significant_strikes_landed_distance=13,
        significant_strikes_attempted_distance=25,
        significant_strikes_landed_clinch=0,
        significant_strikes_attempted_clinch=0,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=1,
        takedowns_attempted=1,
        control_time_minutes=0,
        control_time_seconds=6,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_2_round_4 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="20f57730-725f-5b94-9cc8-9ba0cda81790",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="1fa816e9-e0c1-56b8-a267-4daf7b1e07ab",
        round=4,
        total_strikes_landed=14,
        total_strikes_attempted=30,
        significant_strikes_landed=14,
        significant_strikes_attempted=30,
        significant_strikes_landed_head=4,
        significant_strikes_attempted_head=15,
        significant_strikes_landed_body=8,
        significant_strikes_attempted_body=12,
        significant_strikes_landed_leg=2,
        significant_strikes_attempted_leg=3,
        significant_strikes_landed_distance=12,
        significant_strikes_attempted_distance=26,
        significant_strikes_landed_clinch=2,
        significant_strikes_attempted_clinch=4,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=2,
        control_time_minutes=0,
        control_time_seconds=55,
        submissions_attempted=0,
        reversals=0,
    )

    expected_response_fighter_2_round_5 = FightStatsByRound(
        scraped_at="2000-01-01 00:00:00 UTC",
        fight_stat_by_round_id="447974af-5e0e-50f8-af9e-6f2b6a6d4c4e",
        fight_id="6c8c2ab9-07f2-511f-ac1f-5037fbc2bf42",
        fighter_id="1fa816e9-e0c1-56b8-a267-4daf7b1e07ab",
        round=5,
        total_strikes_landed=15,
        total_strikes_attempted=33,
        significant_strikes_landed=15,
        significant_strikes_attempted=33,
        significant_strikes_landed_head=9,
        significant_strikes_attempted_head=24,
        significant_strikes_landed_body=6,
        significant_strikes_attempted_body=9,
        significant_strikes_landed_leg=0,
        significant_strikes_attempted_leg=0,
        significant_strikes_landed_distance=13,
        significant_strikes_attempted_distance=31,
        significant_strikes_landed_clinch=2,
        significant_strikes_attempted_clinch=2,
        significant_strikes_landed_ground=0,
        significant_strikes_attempted_ground=0,
        knockdowns=0,
        takedowns_landed=0,
        takedowns_attempted=0,
        control_time_minutes=0,
        control_time_seconds=1,
        submissions_attempted=0,
        reversals=0,
    )

    assert parsed_response[0] == expected_response_fighter_1_round_1
    assert parsed_response[1] == expected_response_fighter_1_round_2
    assert parsed_response[2] == expected_response_fighter_1_round_3
    assert parsed_response[3] == expected_response_fighter_1_round_4
    assert parsed_response[4] == expected_response_fighter_1_round_5

    assert parsed_response[5] == expected_response_fighter_2_round_1
    assert parsed_response[6] == expected_response_fighter_2_round_2
    assert parsed_response[7] == expected_response_fighter_2_round_3
    assert parsed_response[8] == expected_response_fighter_2_round_4
    assert parsed_response[9] == expected_response_fighter_2_round_5
